FROM node:22.11.0-alpine

RUN apk update && apk add --no-cache curl ca-certificates && update-ca-certificates

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

EXPOSE 3001 

# Quotable esta usando um certificado expirado. A verificação foi desabilitada apenas para puxar o dados. Não é recomendável em produção.
CMD ["sh", "-c", "NODE_TLS_REJECT_UNAUTHORIZED=0 npm start"]

